apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux101-php
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: linux101-php
  template:
    metadata:
      labels:
        app: linux101-php
        web: linux101
        version: "1.3.4"
    spec:
      containers:
      - name: linux101-php
        image: feliperibeiro95/linux101-php:1.3
        env:
        - name: VERSION
          value: "1.3.4"
        ports:
        - containerPort: 9000
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linux101-php
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: linux101-php
status:
  loadBalancer: {}
